packages:
  - "internal/*"
  - "internal/lint-configs/*"
  - "packages/*"
  - "packages/@core/shared/*"
  - "packages/@core/uikit/*"
  - "packages/@core/forward/*"
  - "packages/@core/helpers"
  - "packages/business/*"
  - "apps/*"
  - "scripts/*"
  - "website"
